Add branch information for install and update package
oh-my-fish/oh-my-fish pull request #685
Opened 2019-02-13 03:26 UTC by YangKeao

See #678.

Find branch information in the repository first and then clone (or pull). If package doesn't have a branch attribute, `master` is used as the default branch.

Maybe more test is needed for it (especially for function `omf.repo.pull`). I only test them on several packages and themes and it works well, but I don't know wethear this project has some unit tests to go through.

2019-02-13 03:28 UTC, YangKeao commented
oh-my-fish/packages-main#82 is related repo pull request

2019-07-23 05:28 UTC, derekstavis commented on pkg/omf/functions/repo/omf.repo.pull.fish
> +  if test "$initial_branch" != $branch
`"$branch"`

2019-07-23 05:28 UTC, derekstavis commented on pkg/omf/functions/repo/omf.repo.pull.fish
> +    __omf.repo.git checkout $branch --quiet
`"$branch"`

2019-07-23 05:28 UTC, derekstavis commented on pkg/omf/functions/repo/omf.repo.pull.fish
> +  if test "$initial_branch" != $branch
`"$branch"`

2019-07-23 05:28 UTC, derekstavis commented on pkg/omf/functions/repo/omf.repo.pull.fish
> +  if test (__omf.repo.git rev-list --count $branch...FETCH_HEAD) -eq 0
`"$branch"`

2019-07-23 05:28 UTC, derekstavis commented on pkg/omf/functions/packages/omf.packages.update.fish
> +    omf.repo.pull $target_path $branch
`"$branch"`

2020-11-29 19:03 UTC, jhillyerd commented
Is this PR dead?  Branch support would be helpful when testing plugin PRs locally.

2020-12-01 14:19 UTC, faho commented
This has a bunch of unadressed comments, so those should either be handled by the author, handled by whoever merges it or this should be closed.

2020-12-01 20:34 UTC, scorphus requested changes
I added a suggestion to the two changes I think are necessary, so they can be committed. Please confirm, @oh-my-fish/core

2020-12-01 20:34 UTC, scorphus commented on pkg/omf/functions/repo/omf.repo.pull.fish
> +  if test "$initial_branch" != $branch
```suggestion
  if test "$initial_branch" != "$branch"
```

2020-12-01 20:34 UTC, scorphus commented on pkg/omf/functions/repo/omf.repo.pull.fish
> +  if test "$initial_branch" != $branch
```suggestion
  if test "$initial_branch" != "$branch"
```

2020-12-02 04:58 UTC, YangKeao commented
Sorry, I have forgotten this PR for a while :crying_cat_face: . I will follow these comments and modify this PR soon :rocket: .

2020-12-02 08:19 UTC, scorphus approved these changes

2021-01-21 19:24 UTC, wzzrd commented
Could this please be merged and released? This would really help me further develop some plugins that I'm working on :)

2021-01-22 12:01 UTC, scorphus approved these changes

2021-01-22 12:02 UTC, merged

2021-02-01 20:24 UTC, wzzrd commented
Cool, thanks!

2022-06-20 16:24 UTC, tennox commented
I think you're close - but I get an error when using `omf channel dev`:

```console
$ omf update
Oh My Fish is up to date.
You are now using Oh My Fish version 7-44-gd428b72.
Updating https://github.com/oh-my-fish/packages-main master... Done!
fatal: couldn't find remote ref refs/heads/master
Could not update fish-functions.
bobthefish is already up-to-date.
default is already up-to-date.
```

2022-06-20 16:24 UTC, tennox commented
well... I see you _just_ pushed another change :rofl: