Fix double slash in index path
oh-my-fish/oh-my-fish pull request #775
Opened 2020-08-16 02:51 UTC by Abdillah

# Description
`XDG_*` or `HOME` variables might contains extra slash at the end of path (I don't know if this is against specification). This double slash might disturb comparison and make them false positive. The consequence is as described in the issue.

The error can happen at the first time fish installed thus might block potential new user for using OMF.

Fixes #774 

**Environment report**

```
Oh My Fish version:   7
OS type:              Linux
Fish version:         fish, version 3.0.2
Git version:          git version 2.25.4
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.

```

# Checklist:

- [x] My code follows the [style guidelines](https://github.com/oh-my-fish/oh-my-fish/blob/master/CONTRIBUTING.md#code-style) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing tests pass locally with my changes 
- [ ] I have updated the SHA256 checksum for the install script

2020-11-30 16:48 UTC, faho commented
Either this or changing to using `realpath` before comparing paths should be merged.

This is a simple fix, *however* because of `string` it requires fish 2.3.0 or later, while the README currently mentions compatibility with 2.2.0.

@scorphus Is fish 2.2.0 compatibility still wanted? If yes, this would have to use `sed` or something instead.

2020-11-30 19:44 UTC, scorphus commented
I think 2.2 compatibility is desired. Ubuntu 16.04 will remain in LTS until 2024, IIRC.

2020-11-30 19:48 UTC, faho commented
>I think 2.2 compatibility is desired. Ubuntu 16.04 will remain in LTS until 2024, IIRC.

There's an [official PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3) for Ubuntu. Personally, I'd just direct users to that.

But, well, it's a maintainer decision. In that case this PR needs to be rewritten to use `sed` or you'll have to use `realpath` (and not the builtin version).

2020-11-30 21:20 UTC, scorphus commented
Dropping 2.2.0 support is probably another, separate discussion. So far I guess we keep supporting it.

Wouldn't `sed`'s different behaviour across systems be a problem? How about something like this:

```fish
function omf.path.join -a prefix -a suffix
  echo $prefix | grep -qE "/\$"
    and echo $prefix$suffix
    or echo $prefix"/"$suffix
end
```

It's not as fast as `string trim` but it's a bit faster than `sed`.

2020-11-30 22:40 UTC, Abdillah commented
> you'll have to use realpath (and not the builtin version).

Why not built-in fish `realpath`?

2020-12-01 05:15 UTC, faho commented
>Why not built-in fish realpath?

Well, because it's not in 2.2.0.

And for compatibility reasons it was decided that any realpath *command* takes precedence (instead of picking a different name for the builtin, which we probably should have just done), so if you do `realpath something` you'll get the command (that might not even exist!), and `builtin realpath something` isn't supported in fish 2.2.0 (only since 2.4.0).

2020-12-01 05:17 UTC, faho commented
>Wouldn't sed's different behaviour across systems be a problem?

@scorphus In this case, i.e. simply trimming a "/"? No.

```fish
echo thing | sed 's:/*$::'
```

should "just work" everywhere?

2020-12-01 19:27 UTC, scorphus requested changes
@Abdillah, please consider the requested changes.

Thanks, @faho.

2020-12-01 19:27 UTC, scorphus commented on pkg/omf/functions/index/omf.index.path.fish
> +    or echo (string trim -r -c "/" $HOME)"/.cache/omf"
```suggestion
    and echo (echo $XDG_CACHE_HOME | sed 's:/*$::')"/omf"
    or echo (echo $HOME | sed 's:/*$::')"/.cache/omf"
```

2020-12-01 22:31 UTC, Abdillah commented on pkg/omf/functions/index/omf.index.path.fish
> +    or echo (string trim -r -c "/" $HOME)"/.cache/omf"
Sure.

2020-12-02 06:12 UTC, scorphus approved these changes
Thanks, @Abdillah!

2020-12-02 06:19 UTC, merged